# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcase\login\login.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {"user-psw": [["xxyyzz", "123456"], ["test123", "1111111"], ["", ""]]}
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("用例描述-登录用例参数化")
        .variables(**{"user": "${ENV(user)}", "psw": "${ENV(psw)}"})
        .base_url("${ENV(base_url)}")
    )

    teststeps = [
        Step(
            RunRequest("step-登录")
            .post("/api/v1/login")
            .with_json({"username": "$user", "password": "$psw"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 3003)
            .assert_length_equal("body.token", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
