# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcase\goods\delete\delete_goods_success.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcase.login.login_success_test import TestCaseLoginSuccess as LoginSuccess


class TestCaseDeleteGoodsSuccess(HttpRunner):

    config = (
        Config("删除商品-成功")
        .variables(
            **{
                "goodsname": "yoyo",
                "goodscode": "${goods_code()}",
                "code": 0,
                "msg": "success!",
            }
        )
        .base_url("${ENV(base_url)}")
    )

    teststeps = [
        Step(RunTestCase("step1-login").call(LoginSuccess).export(*["token"])),
        Step(
            RunRequest("step2-add goods")
            .post("/api/v2/goods")
            .with_headers(**{"Authorization": "Token $token"})
            .with_json({"goodsname": "$goodsname", "goodscode": "$goodscode"})
            .extract()
            .with_jmespath("body.data.id", "delete_sp_id")
            .validate()
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success!")
        ),
        Step(
            RunRequest("step3-delete goods")
            .delete("/api/v2/goods/$delete_sp_id")
            .with_headers(**{"Authorization": "Token $token"})
            .validate()
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success!")
        ),
    ]


if __name__ == "__main__":
    TestCaseDeleteGoodsSuccess().test_start()
