# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcase\goods\delete\delete_goods_null.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcase.login.login_success_test import TestCaseLoginSuccess as LoginSuccess


class TestCaseDeleteGoodsNull(HttpRunner):

    config = (
        Config("删除商品-成功")
        .variables(**{"sp_id_null": 123456, "code": 1000, "msg": "无数据删除"})
        .base_url("${ENV(base_url)}")
    )

    teststeps = [
        Step(RunTestCase("step1-login").call(LoginSuccess).export(*["token"])),
        Step(
            RunRequest("step2-delete goods")
            .delete("/api/v2/goods/$sp_id_null")
            .with_headers(**{"Authorization": "Token $token"})
            .validate()
            .assert_equal("body.code", "$code")
            .assert_equal("body.msg", "$msg")
        ),
    ]


if __name__ == "__main__":
    TestCaseDeleteGoodsNull().test_start()
