# NOTE: Generated By HttpRunner v3.1.5
# FROM: login.har


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLogin(HttpRunner):

    config = Config("testcase description").verify(False)

    teststeps = [
        Step(
            RunRequest("/api/v1/login")
            .post("http://49.235.92.12:8201/api/v1/login")
            .with_headers(
                **{
                    "Accept": "*/*",
                    "Host": "49.235.92.12:8201",
                    "Accept-Encoding": "gzip, deflate, br",
                    "Connection": "keep-alive",
                    "Content-Type": "application/json",
                    "Content-Length": "43",
                }
            )
            .with_json({"username": "test", "password": "123456"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "login success!")
            .assert_equal("body.username", "test")
        ),
    ]


if __name__ == "__main__":
    TestCaseLogin().test_start()
