# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcase\register\register_2.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseRegister2(HttpRunner):

    config = (
        Config("注册用例-重复注册")
        .variables(**{"user": "test123", "psw": "123456", "email": ""})
        .base_url("${ENV(base_url)}")
    )

    teststeps = [
        Step(
            RunRequest("注册")
            .post("/api/v1/register")
            .with_json({"username": "$user", "password": "$psw", "email": "$email"})
            .validate()
            .assert_equal("status_code", 200)
        ),
        Step(
            RunRequest("重复注册")
            .post("/api/v1/register")
            .with_json({"username": "$user", "password": "$psw", "email": "$email"})
            .validate()
            .assert_equal("body.code", 2000)
            .assert_contains("body.msg", "用户已被注册")
        ),
    ]


if __name__ == "__main__":
    TestCaseRegister2().test_start()
