# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcase\part3\login_sign.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginSign(HttpRunner):

    config = (
        Config("用例描述-登录用例")
        .variables(**{"user": "test", "psw": "123456z"})
        .base_url("http://49.235.92.12:8201")
        .export(*["token"])
    )

    teststeps = [
        Step(
            RunRequest("step-登录")
            .setup_hook("${login_sign($request)}")
            .post("/api/v3/login")
            .with_json({"username": "$user", "password": "$psw", "sign": "xxxxx"})
            .extract()
            .with_jmespath("body.token", "token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.msg", "login success!")
            .assert_equal("body.code", 0)
            .assert_equal("body.username", "$user")
            .assert_length_equal("body.token", 40)
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginSign().test_start()
