# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcase\part3\login_params.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginParams(HttpRunner):
    @pytest.mark.parametrize(
        "param", Parameters({"user-password": "${P(data/user_password.csv)}"})
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("用例描述-登录用例")
        .variables(**{"user": "test1", "psw": "123456"})
        .base_url("http://49.235.92.12:8201")
        .export(*["token"])
    )

    teststeps = [
        Step(
            RunRequest("step-登录")
            .post("/api/v1/login")
            .with_json({"username": "$user", "password": "$psw"})
            .extract()
            .with_jmespath("body.token", "token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.msg", "login success!")
            .assert_equal("body.code", 0)
            .assert_equal("body.username", "$user")
            .assert_length_equal("body.token", 40)
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginParams().test_start()
