# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcase\part3\register.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseRegister(HttpRunner):

    config = (
        Config("用例描述-登录用例")
        .variables(**{"user": "${register_user()}", "psw": "1223456"})
        .base_url("http://49.235.92.12:8201")
    )

    teststeps = [
        Step(
            RunRequest("step-登录")
            .post("/api/v1/register")
            .with_json({"username": "$user", "password": "$psw"})
            .validate()
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "register success!")
        ),
    ]


if __name__ == "__main__":
    TestCaseRegister().test_start()
