# NOTE: Generated By HttpRunner v3.1.6
# FROM: testcase\part3\update_info.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcase.part3.login_case_test import TestCaseLoginCase as LoginCase


class TestCaseUpdateInfo(HttpRunner):

    config = (
        Config("修改个人信息")
        .variables(**{"user": "test", "psw": "123456"})
        .base_url("http://49.235.92.12:8201")
    )

    teststeps = [
        Step(RunTestCase("step1-login").call(LoginCase).export(*["token"])),
        Step(
            RunRequest("step2- update info")
            .post("/api/v1/userinfo")
            .with_headers(**{"Authorization": "Token $token"})
            .with_json(
                {"name": "$user", "sex": "M", "age": 20, "mail": "283340479@qq.com"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseUpdateInfo().test_start()
