# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcase\sign\login_invalid_sign.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginInvalidSign(HttpRunner):

    config = (
        Config("登录接口-sign签名不合法")
        .variables(
            **{
                "user": "test2",
                "psw": "123456",
                "code": 3005,
                "msg": "sign签名不合法",
                "len_token": 0,
            }
        )
        .base_url("${ENV(base_url)}")
    )

    teststeps = [
        Step(
            RunRequest("测试步骤：login")
            .post("/api/v3/login")
            .with_json({"username": "$user", "password": "$psw", "sign": "x"})
            .validate()
            .assert_equal("body.code", "$code")
            .assert_equal("body.msg", "$msg")
            .assert_length_equal("body.token", "$len_token")
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginInvalidSign().test_start()
