# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcase\sign\sign_login_csv.yml


import pytest
from httprunner import Parameters


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseSignLoginCsv(HttpRunner):
    @pytest.mark.parametrize(
        "param",
        Parameters(
            {"user-psw-code-msg-len_token": "${P(data/sign_user_password.csv)}"}
        ),
    )
    def test_start(self, param):
        super().test_start(param)

    config = (
        Config("登录sign签名接口")
        .variables(
            **{
                "user": "test",
                "psw": "123456",
                "code": 0,
                "msg": "login success!",
                "len_token": 40,
            }
        )
        .base_url("${ENV(base_url)}")
    )

    teststeps = [
        Step(
            RunRequest("测试步骤：login")
            .setup_hook("${setup_request($request)}")
            .post("/api/v3/login")
            .with_json({"username": "$user", "password": "$psw", "sign": "x"})
            .validate()
            .assert_equal("body.code", "${str_to_int($code)}")
            .assert_equal("body.msg", "$msg")
            .assert_length_equal("body.token", "${str_to_int($len_token)}")
        ),
    ]


if __name__ == "__main__":
    TestCaseSignLoginCsv().test_start()
