# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcase\get_https.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseGetHttps(HttpRunner):

    config = Config("https-blog").verify(False)

    teststeps = [
        Step(RunRequest("step-cnblog").get("https://www.cnblogs.com/yoyoketang")),
    ]


if __name__ == "__main__":
    TestCaseGetHttps().test_start()
