# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcase\get_params.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseGetParams(HttpRunner):

    config = Config("get_goods").base_url("http://49.235.92.12:8201")

    teststeps = [
        Step(
            RunRequest("step-goods")
            .get("/api/v1/goods")
            .with_params(**{"page": 1, "size": 2})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success!")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetParams().test_start()
