# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcase\login_validate.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginValidate(HttpRunner):

    config = (
        Config("用例描述-登录用例")
        .variables(**{"user": "test1", "psw": "123456"})
        .base_url("http://49.235.92.12:8201")
    )

    teststeps = [
        Step(
            RunRequest("step-登录")
            .post("/api/v1/login")
            .with_json({"username": "$user", "password": "$psw"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal('headers."Content-Type"', "application/json")
            .assert_equal('headers."X-Frame-Options"', "SAMEORIGIN")
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "login success!", "msg返回不一致")
            .assert_length_equal("body.token", 40)
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginValidate().test_start()
