# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcase\login_var.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseLoginVar(HttpRunner):

    config = Config("用例描述-登录用例").variables(**{"user": "test1", "psw": "123456"}).export(*["token"])

    teststeps = [
        Step(
            RunRequest("step-登录")
            .post("http://49.235.92.12:8201/api/v1/login")
            .with_json({"username": "$user", "password": "$psw"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.msg", "login success!")
            .assert_equal("body.code", 0)
            .assert_equal("body.username", "$user")
            .assert_length_equal("body.token", 40)
        ),
        Step(
            RunRequest("step-登录 test")
            .with_variables(**{"user": "test", "psw": "123456"})
            .post("http://49.235.92.12:8201/api/v1/login")
            .with_json({"username": "$user", "password": "$psw"})
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.msg", "login success!")
            .assert_equal("body.code", 0)
            .assert_equal("body.username", "$user")
            .assert_length_equal("body.token", 40)
        ),
    ]


if __name__ == "__main__":
    TestCaseLoginVar().test_start()
