# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcase\userinfo.yml


import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent.parent))


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase

from testcase.login_test import TestCaseLogin as Login


class TestCaseUserinfo(HttpRunner):

    config = (
        Config("用例描述-登录用例")
        .variables(**{"user": "test1", "psw": "123456"})
        .base_url("http://49.235.92.12:8201")
        .export(*["token"])
    )

    teststeps = [
        Step(RunTestCase("step-登录").call(Login).export(*["token"])),
        Step(
            RunRequest("step-userinfo")
            .post("/api/v1/userinfo")
            .with_headers(**{"Authorization": "Token $token"})
            .with_json(
                {"name": "$user", "sex": "M", "age": 20, "mail": "283340479@qq.com"}
            )
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.code", 0)
        ),
    ]


if __name__ == "__main__":
    TestCaseUserinfo().test_start()
