# NOTE: Generated By HttpRunner v3.1.5
# FROM: testcase\address\get_address_null.yml


from httprunner import HttpRunner, Config, Step, RunRequest, RunTestCase


class TestCaseGetAddressNull(HttpRunner):

    config = (
        Config("未添加过收件人地址，查询为空")
        .variables(**{"user": "${register_user()}", "psw": "1223456"})
        .base_url("${ENV(base_url)}")
    )

    teststeps = [
        Step(
            RunRequest("step1-注册新用户")
            .post("/api/v1/register")
            .with_json({"username": "$user", "password": "$psw", "email": ""})
            .validate()
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "register success!")
        ),
        Step(
            RunRequest("step2-登录")
            .post("/api/v1/login")
            .with_json({"username": "$user", "password": "$psw"})
            .extract()
            .with_jmespath("body.token", "token")
            .validate()
            .assert_equal("status_code", 200)
            .assert_equal("body.msg", "login success!")
        ),
        Step(
            RunRequest("step3-get address")
            .get("/api/v2/address")
            .with_headers(**{"Authorization": "Token $token"})
            .validate()
            .assert_equal("body.code", 0)
            .assert_equal("body.msg", "success!")
            .assert_equal("body.data.tel", "")
            .assert_equal("body.data.name", "")
            .assert_equal("body.data.address", "")
            .assert_equal("body.data.postal", "")
        ),
    ]


if __name__ == "__main__":
    TestCaseGetAddressNull().test_start()
